N8N_JSON_URL = "https://yuya.app.n8n.cloud/webhook/latest"

OPENAI_API_KEY = "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"